export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN SUCCESS';
export const LOGIN_FAILURE = 'LOGIN FAILURE';
export const DISPLAY_NOTIFICATION_DRAWER = 'DISPLAY NOTIFICATION DRAWER';
export const HIDE_NOTIFICATION_DRAWER = 'HIDE NOTIFICATION DRAWER';
